Diagram fill
nvs174/Coursework pull request #3
Opened 2024-04-13 09:59 UTC by nvs174

2024-04-20 14:45 UTC, lamer0k commented on source/RtosWrapper/Application/Task/imeasurementscontroller.h
> +class IMeasurementsController
убрать в папку Application/Contracts

2024-04-20 14:45 UTC, lamer0k commented on source/RtosWrapper/Application/Task/imeasurementscontroller.h
> +private:
удалить

2024-04-20 14:46 UTC, lamer0k commented on source/RtosWrapper/Application/Task/measuretask.cpp
> +    MeasureTask(IMeasurementsController& controller) : mController(controller){}
выравнивание.

2024-04-20 14:46 UTC, lamer0k commented on source/RtosWrapper/Application/Task/measuretask.cpp
> +  virtual void Execute() override
virtual удалить

2024-04-20 14:46 UTC, lamer0k commented on source/RtosWrapper/Application/Task/measuretask.cpp
> +
удалить лишние строчки

2024-04-20 14:47 UTC, lamer0k commented on source/RtosWrapper/main.cpp
> +
удалить лишние инклуды

2024-04-20 14:47 UTC, lamer0k commented on source/RtosWrapper/main.cpp
> +
строчик лишние убрать

2024-04-20 14:47 UTC, lamer0k commented on source/RtosWrapper/main.cpp
> +Bme280 bme (spi);
куда передаются?

2024-04-20 14:48 UTC, lamer0k commented on source/RtosWrapper/Application/Bme280/bme280.cpp
> +class Bme280: public IMeasurementsController
где декларация клксса?

2024-04-20 14:48 UTC, lamer0k commented on source/RtosWrapper/Application/Bme280/bme280.cpp
> +#include "imeasurementscontroller.h"
подписи для инклудников

2024-04-20 14:52 UTC, lamer0k commented on source/RtosWrapper/Application/SPI/ispi.h
> +class ISpi
Все не так. SPI - потому что - у него должен быть простой интерфейс.

Типа Configure(), ReadByte(), WriteByte(); ReadWord()

2024-04-20 14:53 UTC, lamer0k commented on source/RtosWrapper/Application/SPI/ispi.h
> +class ISpi
Удалить полностью SPI  и сделать его в отдельной задаче.

2024-04-20 14:55 UTC, lamer0k commented on source/RtosWrapper/Application/Bme280/registerbme280.h
> +#define BME280_ADDRESS 0x76<<1 /*����� BME280, p.32, 6.2*/
Коментарий написать . Файл взят с.....

2024-04-20 14:55 UTC, lamer0k commented on source/RtosWrapper/Application/Bme280/bme280.cpp
> +    id = mspi.ModeRead(BME280_REG_ID);
TODO что чисто для проверки

2024-04-20 14:55 UTC, lamer0k commented on source/RtosWrapper/Application/Bme280/bme280.cpp
> +  uint8_t id;
удалить.

2024-04-27 15:12 UTC, lamer0k commented on source/RtosWrapper/Application/Contracts/idatanotifyp.h
> +#include <iostream>
для чего?

2024-04-27 15:13 UTC, lamer0k commented on source/RtosWrapper/Application/Contracts/idatanotifyh.h
> +#include <iostream>
Для чего?

2024-04-27 15:13 UTC, lamer0k commented on source/RtosWrapper/Application/Contracts/idatanotifyt.h
> +#include <iostream>
для чего?

2024-04-27 15:14 UTC, lamer0k commented on source/RtosWrapper/Application/Contracts/ifloatdataprovider.h
> +  virtual void GetData(float* data)= 0;
Зачем указатель?

2024-04-27 15:24 UTC, lamer0k commented on source/RtosWrapper/Application/Contracts/ispi.h
> +#include <iostream>
Удалить весь файл

2024-04-27 15:24 UTC, lamer0k commented on source/RtosWrapper/Application/Contracts/itransfer.h
> +class ITransfer
Удалить весь файл

2024-04-27 15:24 UTC, lamer0k commented on source/RtosWrapper/Application/SPI/spi.cpp
> +class Spi: public ISpi
Удалить весь файл

2024-04-27 15:24 UTC, lamer0k commented on source/RtosWrapper/Application/Task/sendtask.cpp
> +class SendTask: public OsWrapper::Thread<128>
Удалить пока всю задача

2024-04-27 15:25 UTC, lamer0k commented on source/RtosWrapper/Application/Usart/usart.cpp
> +class Usart: public ITransfer
Удалить весб файл

2024-04-27 15:25 UTC, lamer0k commented on DescriptionSPI.adoc
> +== Подключение SPI
Удалить весь файл

2024-04-27 15:25 UTC, lamer0k commented on DescriptionSendTask.adoc
> +== Заполнение классов Usart, SendTask
Удалить весь файл

2024-04-27 15:26 UTC, lamer0k commented on source/RtosWrapper/Application/Bme280/bme280.cpp
> +#include "imeasurementscontroller.h" // for Update()
Удалить из запроса

2024-04-27 15:26 UTC, lamer0k commented on source/RtosWrapper/Application/Bme280/registerbme280.h
> +/*Информация о регистрах взята из "BME280 Combined humidity and pressure sensor"*/
Удалить из запроса

2024-04-27 15:26 UTC, lamer0k commented on source/RtosWrapper/Application/Contracts/ibme280.h
> +class IBme280
Удалить из запроса

2024-04-27 15:32 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/calculationdewpoint.cpp
> +    float const a = 17.27f;
constexpr float a =  17.27f;

2024-04-27 15:33 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/calculationdewpoint.cpp
> +    float const b = 237.7f;
constexpr float b = 237.7f;

2024-04-27 15:33 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/calculationdewpoint.cpp
> +    mdataT.GetData(&measuredT);
const auto measuredT = mdataT.GetData();

2024-04-27 15:34 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/calculationdewpoint.cpp
> +    mdataH.GetData(&measuredH);
const auto measuredH =...

2024-04-27 15:34 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/calculationdewpoint.cpp
> +    measuredY = ((a * measuredT) / (b + measuredT)) + log(measuredH);
float measureY =

2024-04-27 15:35 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/calculationdewpoint.cpp
> +  float measuredD;
value

2024-04-27 15:36 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/calculationdewpoint.cpp
> +   *data = measuredD;
return value;

2024-04-27 15:36 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/humidity.cpp
> +   float measuredH;
value

2024-04-27 15:36 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/press.cpp
> +#include <iostream> // for std::
для чего?

2024-04-27 15:36 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/humidity.cpp
> +#include <iostream> // for std::
для чего?

2024-04-27 15:37 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/calculationdewpoint.cpp
> +#include <iostream> // for std::
для чего?

2024-04-27 15:37 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/temperature.cpp
> +#include <iostream> // for std::
Для чего?

2024-04-27 15:38 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/temperature.cpp
> +    auto measuredX = ((adcT / 16) - digT1);
Тут, непонятно что какого типа и какой тип будет у measuredX

2024-04-27 15:39 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/temperature.cpp
> +    measuredT = measuredX * digT1 + ((measuredX * measuredX * digT3) / 65536);
И здесь тоже

2024-04-27 15:41 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/press.cpp
> +    measuredP = (adcP / 16) * 0.18f;
каст

2024-04-27 15:43 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/humidity.cpp
> +    measuredH = adcH * 0.008;
каст

2024-04-27 15:43 UTC, lamer0k commented on source/RtosWrapper/Application/Task/measuretask.cpp
> +  IMeasurementsUpdate& mUpdateT;
temperature

2024-04-27 15:43 UTC, lamer0k commented on source/RtosWrapper/Application/Task/measuretask.cpp
> +  IMeasurementsUpdate& mUpdatePoint;
dewPoint

2024-04-27 15:47 UTC, lamer0k requested changes
Удалить лишние классы и поправить замечания

2024-05-04 12:38 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/calculationdewpoint.cpp
> +    constexpr float a = 17.27f;
комментарий откуда эти числа.

2024-05-04 12:40 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/humidity.cpp
> +    value = static_cast<float>(adcH) * 0.008f;
Magic Number

2024-05-04 12:42 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/press.cpp
> +    value = (static_cast<float>(adcP) / 16.0f) * 0.18f;
Magic Number

2024-05-04 12:42 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/temperature.cpp
> +    auto measuredX = ((static_cast<float>(adcT) / 16.0f) - static_cast<float>(digT1));
Числа все надо в константы с понятными именами.

2024-05-04 12:46 UTC, lamer0k commented on source/RtosWrapper/Application/Contracts/idatanotifyh.h
> +#include <iostream> // for int16_t
для Int16_t <cstdint>

2024-05-04 12:46 UTC, lamer0k commented on source/RtosWrapper/Application/Contracts/idatanotifyh.h
> +#include <iostream> // for int16_t
std::int16_t

2024-05-04 12:48 UTC, lamer0k commented on source/RtosWrapper/Application/Task/measuretask.cpp
> +class MeasureTask: public OsWrapper::Thread<128>
надо сделать measuretask.h  и measuretask.cpp

2024-05-04 12:52 UTC, lamer0k commented on source/RtosWrapper/main.cpp
> +#include "spi.cpp" // for SPI
Нельзя инклудить cpp файлы. только *.h
Удалить все лишний файлы, которых нет в запросе, spi, uasrt, bme280.

2024-05-04 13:01 UTC, lamer0k requested changes
Разделить cpp файлы на заголовочник с декларацией класса и срр файл с определением класса

2024-05-04 15:08 UTC, nvs174 commented on source/RtosWrapper/Application/PhysicalValues/calculationdewpoint.cpp
> +    constexpr float a = 17.27f;
добавил

2024-05-04 15:08 UTC, nvs174 commented on source/RtosWrapper/Application/PhysicalValues/humidity.cpp
> +    value = static_cast<float>(adcH) * 0.008f;
указал через переменную

2024-05-04 15:08 UTC, nvs174 commented on source/RtosWrapper/Application/PhysicalValues/press.cpp
> +    value = (static_cast<float>(adcP) / 16.0f) * 0.18f;
указала через переменную

2024-05-04 15:08 UTC, nvs174 commented on source/RtosWrapper/Application/PhysicalValues/temperature.cpp
> +    auto measuredX = ((static_cast<float>(adcT) / 16.0f) - static_cast<float>(digT1));
указал константы

2024-05-04 15:08 UTC, nvs174 commented on source/RtosWrapper/Application/Contracts/idatanotifyh.h
> +#include <iostream> // for int16_t
заменил на std::

2024-05-04 15:08 UTC, nvs174 commented on source/RtosWrapper/Application/Task/measuretask.cpp
> +class MeasureTask: public OsWrapper::Thread<128>
Исправил

2024-05-04 15:08 UTC, nvs174 commented on source/RtosWrapper/main.cpp
> +#include "spi.cpp" // for SPI
Я добавил классы: spi, usart, bme280, но они пустые

2024-05-07 14:37 UTC, lamer0k commented on source/RtosWrapper/Application/PhysicalValues/calculationdewpoint.cpp
> +  float measuredY = ((a * temperature) / (b + temperature)); //+ log(humidity);
TODO добавить

2024-05-07 14:42 UTC, lamer0k approved these changes

2024-05-10 09:33 UTC, merged